### ISSUE TITLE
Works, but payment processor still charges original amount

### ISSUE THREAD

**Issue by TectonicKestrel** [meanbee/magento2-tax-rounding#2]
I am hoping this is still maintained.
I installed this module and visually it appears to work, but when i use Stripe as my payment processor and choose to send an invoice and hosted checkout page to a customer (for example when i process an order manually) it still shows the original order total.

If i use this module and 2 x £6.67 ex VAT is added to the cart a total of £16 inc VAT will be displayed, this is how it should be and shows the module working, but when a Stripe invoice is generated and a hosted checkout page is sent to my customer they are still charged £16.01.

I am unsure whether this is your module not correcting the price evrywhere in magento or that stripe is doing its own rounding and reverting back to the magento way.
Stripe dont seem to be much help when asking about their module, they keep saying to "ask magento" no matter what the issue is. If you can rule out your module that would be great.

**Comment by bobbyshaw** [comment]
Closing as this repo is no longer maintained and will be marked as read-only.
